Repository cordis-lib/cordis, pull requests merged in 2021-03, with the labels that each got.

#41 fix(rest/router): generic types for making requests
  libs/rest/src/Bucket.ts
  libs/rest/src/Fetch.ts
  libs/rest/src/RestManager.ts
  libs/routers/src/IRouter.ts
Labels: p: medium, semver: patch, t: bug fix

#42 fix: make options.files optional
  libs/rest/src/RestManager.ts
Labels: p: medium, t: bug fix

#45 make put data optional
  libs/rest/src/RestManager.ts
  libs/routers/src/IRouter.ts
Labels: p: low, semver: patch, t: bug fix

#47 meta stuff
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  libs/bitfield/README.md
  libs/brokers/README.md
  libs/common/README.md
  libs/error/README.md
  libs/gateway/README.md
  libs/queue/README.md
  libs/redis-store/README.md
  libs/rest/README.md
  libs/routers/README.md
  libs/snowflake/README.md
  libs/store/README.md
  media/cordis_transparent.png
  services/gateway/README.md
Labels: meta, p: low

#48 chore: fix npm deployment
  package.json
  pnpm-lock.yaml
Labels: meta, p: low, semver: patch

#49 fix(WebsocketConnection): handle unexpected close code properly
  libs/bitfield/package.json
  libs/brokers/package.json
  libs/common/package.json
  libs/error/package.json
  libs/gateway/package.json
  libs/gateway/src/websocket/WebsocketConnection.ts
  libs/queue/package.json
  libs/redis-store/package.json
  libs/rest/package.json
  libs/routers/package.json
  libs/snowflake/package.json
  libs/store/package.json
  package.json
  pnpm-lock.yaml
  services/gateway/Dockerfile
  services/gateway/package.json
Labels: p: high, semver: patch

#53 fix(functions/test): halt test can no longer randomly fail
  libs/common/src/functions/functions.test.ts
Labels: p: low

#51 feat(repo): meta thread issue template & other regressions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/meta_thread.md
  README.md
Labels: t: meta

#58 replace cordis.didinele.me with cordis.js.org
  README.md
  libs/bitfield/README.md
  libs/brokers/README.md
  libs/common/README.md
  libs/error/README.md
  libs/gateway/README.md
  libs/queue/README.md
  libs/redis-store/README.md
  libs/rest/README.md
  libs/routers/README.md
  libs/snowflake/README.md
  libs/store/README.md
Labels: t: meta

#32 BREAKING!: feat @cordis/util
  README.md
  libs/common/src/functions/functions.test.ts
  libs/common/src/functions/index.ts
  libs/rest/src/RestManager.ts
  libs/routers/src/IRouter.ts
  libs/util/README.md
  libs/util/package.json
  libs/util/src/Snowflake.test.ts
  libs/util/src/Snowflake.ts
  libs/util/src/embed.test.ts
  libs/util/src/embed.ts
  libs/util/src/error.ts
  libs/util/src/index.ts
  libs/util/src/makeDiscordCdnUrl.test.ts
  libs/util/src/makeDiscordCdnUrl.ts
  libs/util/src/restUtils.ts
  libs/util/tsconfig.json
  pnpm-lock.yaml
Labels: p: medium, semver: major, t: feature

#35 chore: remove redundant methods from redis-store
  libs/redis-store/src/index.ts
Labels: semver: major, tech: redis

#52 fix(gateway/gateway-service): remove built-in caching
  libs/gateway/package.json
  libs/gateway/src/websocket/Cluster.ts
  libs/gateway/src/websocket/WebsocketConnection.ts
  pnpm-lock.yaml
  services/gateway/Dockerfile
  services/gateway/package.json
  services/gateway/src/index.ts
Labels: p: high, semver: major

#59 BREAKING!: merge routers with rest
  README.md
  libs/gateway/src/websocket/Cluster.ts
  libs/rest/README.md
  libs/rest/src/Bucket.ts
  libs/rest/src/IRouter.ts
  libs/rest/src/Rest.ts
  libs/rest/src/index.ts
  libs/rest/src/rest.test.ts
  libs/rest/src/restRouter.test.ts
  libs/rest/src/restRouter.ts
  libs/routers/README.md
  libs/routers/package.json
  libs/routers/src/index.ts
  libs/routers/tsconfig.json
  libs/util/src/restUtils.ts
Labels: p: high, semver: major

#60 feat(gateway): resuming when connecting for the first time
  libs/gateway/src/websocket/Cluster.ts
  libs/gateway/src/websocket/WebsocketConnection.ts
Labels: semver: minor, t: feature

#61 feat(gateway-service): support code injection
  libs/common/src/constants.ts
  pnpm-lock.yaml
  services/gateway/package.json
  services/gateway/src/index.ts
Labels: semver: minor, t: feature

#62 chore: improve npm scripts
  .github/workflows/quality.yml
  libs/bitfield/package.json
  libs/brokers/package.json
  libs/common/package.json
  libs/error/package.json
  libs/gateway/package.json
  libs/queue/package.json
  libs/redis-store/package.json
  libs/rest/package.json
  libs/store/package.json
  libs/util/package.json
  package.json
  pnpm-lock.yaml
  services/gateway/Dockerfile
  services/gateway/package.json
Labels: p: low, t: meta

#65 fix(WebscoketConnection): actually identify if not reconnecting
  libs/gateway/src/websocket/WebsocketConnection.ts
Labels: p: high, semver: minor, t: bug

#66 fix(restUtil): weebhook data problems
  libs/util/src/restUtils.ts
Labels: p: high, semver: patch, t: bug

#67 fix(util): add discord-api-types dependency
  libs/util/package.json
  pnpm-lock.yaml
Labels: p: high, semver: patch, t: bug

#68 chore: fix readme links
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: p: low, t: meta

#69 0.2.3 changes
  .eslintignore
  .github/ISSUE_TEMPLATE/feature_request.md
  libs/bitfield/package.json
  libs/brokers/package.json
  libs/common/package.json
  libs/error/package.json
  libs/gateway/package.json
  libs/queue/package.json
  libs/redis-store/package.json
  libs/rest/package.json
  libs/rest/src/Bucket.ts
  libs/rest/src/mutex/Mutex.ts
  libs/rest/src/rest.test.ts
  libs/store/package.json
  libs/util/package.json
  libs/util/src/restUtils.ts
  package.json
  pnpm-lock.yaml
  services/gateway/package.json
Labels: p: high, semver: minor, t: bug, t: meta
