Repository cordis-lib/cordis, pull requests merged in 2021-02, with the labels that each got.

#7 fix(RedisStore): async iterator now uses zoomy streams
  libs/gateway/package.json
  libs/redis-store/src/index.ts
  pnpm-lock.yaml
Labels: tech: redis

#12 fix(*): various problems
  libs/bitfield/.npmignore
  libs/bitfield/README.md
  libs/bitfield/package.json
  libs/brokers/.npmignore
  libs/brokers/README.md
  libs/brokers/package.json
  libs/common/.npmignore
  libs/common/README.md
  libs/common/package.json
  libs/error/.npmignore
  libs/error/README.md
  libs/error/package.json
  libs/gateway/.npmignore
  libs/gateway/README.md
  libs/gateway/package.json
  libs/queue/.npmignore
  libs/queue/README.md
  libs/queue/package.json
  libs/redis-store/.npmignore
  libs/redis-store/README.md
  libs/redis-store/package.json
  libs/rest/.npmignore
  libs/rest/README.md
  libs/rest/package.json
  libs/routers/.npmignore
  libs/routers/README.md
  libs/routers/package.json
  libs/routers/src/restRouter.ts
  libs/snowflake/.npmignore
  libs/snowflake/README.md
  libs/snowflake/package.json
  libs/store/.npmignore
  libs/store/README.md
  libs/store/package.json
  package.json
  pnpm-lock.yaml
  services/gateway/package.json
Labels: p: high, semver: minor, t: bug

#19 Fix various breaking bugs/implement QOL
  libs/bitfield/.npmignore
  libs/bitfield/package.json
  libs/brokers/.npmignore
  libs/brokers/package.json
  libs/brokers/src/brokers/routing/RoutingClient.ts
  libs/common/.npmignore
  libs/common/package.json
  libs/error/.npmignore
  libs/error/package.json
  libs/gateway/.npmignore
  libs/gateway/package.json
  libs/gateway/src/error.ts
  libs/gateway/src/websocket/Cluster.ts
  libs/gateway/src/websocket/WebsocketConnection.ts
  libs/queue/.npmignore
  libs/queue/package.json
  libs/redis-store/.npmignore
  libs/redis-store/package.json
  libs/rest/.npmignore
  libs/rest/package.json
  libs/routers/.npmignore
  libs/routers/package.json
  libs/routers/src/IRouter.ts
  libs/snowflake/.npmignore
  libs/snowflake/package.json
  libs/store/.npmignore
  libs/store/package.json
  package.json
  pnpm-lock.yaml
  services/gateway/Dockerfile
  services/gateway/package.json
  services/gateway/src/index.ts
Labels: semver: patch, t: bug fix, t: feature implementation

#26 fix: add a RequestBodyData type and replace in appropriate areas
  libs/rest/src/Bucket.ts
  libs/rest/src/Fetch.ts
  libs/rest/src/RestManager.ts
  libs/routers/src/IRouter.ts
Labels: p: low, semver: patch, t: bug fix

#24 fix(GatewayService): optimize size
  services/gateway/Dockerfile
Labels: s: wip, semver: patch, tech: docker

#30 fix(IRouter): return types
  libs/routers/src/IRouter.ts
  libs/routers/src/restRouter.test.ts
Labels: semver: patch, t: bug fix

#31 fix(*): npm deployment
  libs/bitfield/.npmignore
  libs/bitfield/package.json
  libs/brokers/.npmignore
  libs/brokers/package.json
  libs/common/.npmignore
  libs/common/package.json
  libs/error/.npmignore
  libs/error/package.json
  libs/gateway/.npmignore
  libs/gateway/package.json
  libs/queue/.npmignore
  libs/queue/package.json
  libs/redis-store/.npmignore
  libs/redis-store/package.json
  libs/rest/.npmignore
  libs/rest/package.json
  libs/routers/.npmignore
  libs/routers/package.json
  libs/snowflake/.npmignore
  libs/snowflake/package.json
  libs/store/.npmignore
  libs/store/package.json
Labels: semver: patch, t: bug fix

#33 chore: bump local package dep versions and add contribs
  libs/bitfield/package.json
  libs/brokers/package.json
  libs/common/package.json
  libs/error/package.json
  libs/gateway/package.json
  libs/queue/package.json
  libs/redis-store/package.json
  libs/rest/package.json
  libs/routers/package.json
  libs/snowflake/package.json
  libs/store/package.json
  pnpm-lock.yaml
Labels: p: low

#34 workflows: add docs deploy workflow
  .github/workflows/docs.yml
Labels: p: low

#36 fix(Cluster): redis store construction
  libs/gateway/src/websocket/Cluster.ts
Labels: semver: patch, t: bug fix, tech: redis

#39 emergency fix for docs deploy workflow
  .github/workflows/docs.yml
Labels: p: high

#40 emergency fix for docs deploy workflow no.2 electric boogalo
  .github/workflows/docs.yml
Labels: p: high
